language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t osherkoren/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true osherkoren/docker-react npm run test